### ISSUE TITLE
Smart Charging Status Switch - reporting unexpected values.

### ISSUE THREAD

**Issue by tobbensoft** [EvTheFuture/SmartCharging#8]
Switch for Enable/Disable Smartcharging is reporting "Disabled by user" when there is no need to charge and switch is on.

![image](https://user-images.githubusercontent.com/46381052/101195831-4bb75b00-3660-11eb-8d2f-9b50692c3315.png)

Values are retained even when switch have been toggled.

![image](https://user-images.githubusercontent.com/46381052/101196232-c1232b80-3660-11eb-83c0-6fa153facde4.png)

IMO time slots should be removed when switch -> off. And recalculated when switch changes state to on. 
Then we should always end up with a valid state.

The name should also be changed so it's not the same as the sensor. :).

 (Or it's just that they are in some states are displaying the same information which makes it a little confusing.)

**Comment by EvTheFuture** [comment]
My guess is that you are watching the switch and not the sensor. There was a bug where the sensor's attributes were used when updating the switch. 0.42 alpha should fix that, can you please give it a try?

**Comment by tobbensoft** [comment]
Friendly name seems correct now.

Switch has stopped working, but setting through Developer Tools works.

![image](https://user-images.githubusercontent.com/46381052/101207218-9a6cf100-3670-11eb-96a1-51903e90594f.png)

Error from Appdaemon log: (when activating switch)

```2020-12-04 20:35:51.003053 ERROR charge_ev_when_cheepest: Exception when handling event
Traceback (most recent call last):
  File "/config/appdaemon/apps/ev_charge_control/ev_charge_control.py", line 286, in handle_incoming_event
    attributes=self.data[key]["attributes"],
TypeError: string indices must be integers
2020-12-04 20:36:16.401340 ERROR charge_ev_when_cheepest: Exception when handling event
Traceback (most recent call last):
  File "/config/appdaemon/apps/ev_charge_control/ev_charge_control.py", line 286, in handle_incoming_event
    attributes=self.data[key]["attributes"],
TypeError: string indices must be integers
```
As before this log entry in HA log

```
WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.charge_ev_when_cheepest_active
```

**Comment by tobbensoft** [comment]
Seems to work in latest version.
